part1: smsh2.c splitline.c execute.c
	gcc -o smsh2 smsh2.c splitline.c execute.c
part2: smsh3.c splitline.c execute.c
	gcc -o smsh3 smsh3.c splitline.c execute.c
part3: smsh4.c splitline.c execute.c
	gcc -o smsh4 smsh3.c splitline.c execute.c
clean:
	rm *.o out
